accumulate_grad_batches: 1
batch_size: 16
epochs: 10
lr: 0.000135
test_path: /home/wanhee/SATbot2.0/model/emotion_data/my_test.txt
train_path: /home/wanhee/SATbot2.0/model/emotion_data/my_train.txt
val_path: /home/wanhee/SATbot2.0/model/emotion_data/my_val.txt
warmup_steps: 100
